"""Checking model updates

Revision ID: 05fb6564fffd
Revises: 3c5507563253
Create Date: 2025-01-06 12:19:09.827459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fb6564fffd'
down_revision = '3c5507563253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.String(length=100), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('mode_of_transport', sa.String(length=50), nullable=False),
    sa.Column('incoterms', sa.String(length=50), nullable=False),
    sa.Column('cargo_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('base_freight_charges', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('additional_charges', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('services_included', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivery_time_estimate', sa.Integer(), nullable=False),
    sa.Column('special_instructions', sa.String(length=300), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id', 'quotation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotations')
    # ### end Alembic commands ###
