"""added id1

Revision ID: 2e7e3ac323e5
Revises: 827ad0a7500b
Create Date: 2025-01-08 13:46:58.319315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7e3ac323e5'
down_revision = '827ad0a7500b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.String(length=100), nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.String(length=100), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('mode_of_transport', sa.String(length=50), nullable=False),
    sa.Column('incoterms', sa.String(length=50), nullable=False),
    sa.Column('cargo_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('base_freight_charges', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('additional_charges', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('services_included', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivery_time_estimate', sa.Integer(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('idx_quotation_id', ['quotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index('idx_quotation_id')

    op.drop_table('quotations')
    # ### end Alembic commands ###
