"""added id

Revision ID: 52723c9d1f91
Revises: 2c743a637f47
Create Date: 2025-01-06 13:02:55.852781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52723c9d1f91'
down_revision = '2c743a637f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
