"""added id

Revision ID: 7bb70cc23e28
Revises: 7644795e748a
Create Date: 2025-01-06 16:39:29.227536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bb70cc23e28'
down_revision = '7644795e748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_of_issue',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('volume',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('base_freight_charges',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('additional_charges',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('discount',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('services_included',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('delivery_time_estimate',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('remarks',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('delivery_time_estimate',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('services_included',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('additional_charges',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('base_freight_charges',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('date_of_issue',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('quotation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
