"""Initial migration

Revision ID: 7e981d905912
Revises: 
Create Date: 2024-10-22 15:02:31.310456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e981d905912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('job_id')

    op.drop_table('jobs')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('invoice_number')

    op.drop_table('invoices')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('id')

    op.drop_table('customers')
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('name')

    op.drop_table('status')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('tracking_number')

    op.drop_table('shipments')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('user_roles_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_roles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_roles_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_roles_ibfk_2', 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    op.create_table('shipments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tracking_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('weight', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('volume', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estimated_delivery', mysql.TIMESTAMP(), nullable=True),
    sa.Column('actual_delivery', mysql.TIMESTAMP(), nullable=True),
    sa.Column('current_location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index('tracking_number', ['tracking_number'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('status',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('customers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('invoices',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('issued_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('due_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('paid', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('invoice_number', ['invoice_number'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('jobs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('job_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('origin', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('destination', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('job_id', ['job_id'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
