"""added id

Revision ID: 827ad0a7500b
Revises: 943a4e1d348d
Create Date: 2025-01-08 13:44:50.711502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '827ad0a7500b'
down_revision = '943a4e1d348d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date_of_issue',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('expiration_date',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('volume',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('base_freight_charges',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('additional_charges',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('services_included',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('delivery_time_estimate',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('special_instructions',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('remarks',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index('idx_quotation_id', ['quotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index('idx_quotation_id')
        batch_op.alter_column('remarks',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('special_instructions',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('delivery_time_estimate',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('services_included',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('additional_charges',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('base_freight_charges',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('volume',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('expiration_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('date_of_issue',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('quotation_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
