"""Checking model updates

Revision ID: 91872c80845a
Revises: 49fe4a655db4
Create Date: 2024-11-07 00:25:01.382928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91872c80845a'
down_revision = '49fe4a655db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=150), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_due', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('issued_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('amount')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('volume_weight', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estimated_arrival', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('estimated_arrival')
        batch_op.drop_column('destination')
        batch_op.drop_column('origin')
        batch_op.drop_column('volume_weight')
        batch_op.drop_column('weight')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('issued_date')
        batch_op.drop_column('amount_due')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
