"""added id

Revision ID: 943a4e1d348d
Revises: 7bb70cc23e28
Create Date: 2025-01-06 17:44:18.316143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '943a4e1d348d'
down_revision = '7bb70cc23e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('date_of_issue',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('volume',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('base_freight_charges',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('additional_charges',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('services_included',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('delivery_time_estimate',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('delivery_time_estimate',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('services_included',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('additional_charges',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('base_freight_charges',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('volume',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('expiration_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('date_of_issue',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('quotation_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
